//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movieStar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SW_MYBATIS_TESTEntities2 : DbContext
    {
        public SW_MYBATIS_TESTEntities2()
            : base("name=SW_MYBATIS_TESTEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<CATEGORY_SELECT_Result> CATEGORY_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CATEGORY_SELECT_Result>("CATEGORY_SELECT");
        }
    
        public virtual ObjectResult<CATEGORY_SELECT1_Result> CATEGORY_SELECT1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CATEGORY_SELECT1_Result>("CATEGORY_SELECT1");
        }
    }
}
