//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movieStar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MVC_BOARD_TESTEntities : DbContext
    {
        public MVC_BOARD_TESTEntities()
            : base("name=MVC_BOARD_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_BOARD> T_BOARD { get; set; }
        public virtual DbSet<T_BOARD_02> T_BOARD_02 { get; set; }
        public virtual DbSet<T_BOARD_CMT> T_BOARD_CMT { get; set; }
        public virtual DbSet<T_CODE> T_CODE { get; set; }
    
        public virtual ObjectResult<SP_SSW_BOARD_CMT_DETAIL_SEL_03_Result> SP_SSW_BOARD_CMT_DETAIL_SEL_03(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SSW_BOARD_CMT_DETAIL_SEL_03_Result>("SP_SSW_BOARD_CMT_DETAIL_SEL_03", iDXParameter);
        }
    
        public virtual ObjectResult<SP_SSW_BOARD_CMT_SEL_Result> SP_SSW_BOARD_CMT_SEL(Nullable<int> cASE, ObjectParameter nEW_CMT_IDX)
        {
            var cASEParameter = cASE.HasValue ?
                new ObjectParameter("CASE", cASE) :
                new ObjectParameter("CASE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SSW_BOARD_CMT_SEL_Result>("SP_SSW_BOARD_CMT_SEL", cASEParameter, nEW_CMT_IDX);
        }
    
        public virtual int SP_SSW_BOARD_PAGING_CNT(string sEARCH_COL, string sEARCH_KEY)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYParameter = sEARCH_KEY != null ?
                new ObjectParameter("SEARCH_KEY", sEARCH_KEY) :
                new ObjectParameter("SEARCH_KEY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SSW_BOARD_PAGING_CNT", sEARCH_COLParameter, sEARCH_KEYParameter);
        }
    
        public virtual int SP_SSW_BOARD_PAGING_SEL(string sEARCH_COL, string sEARCH_KEY, string sORT_COL, string sORT_DIR, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYParameter = sEARCH_KEY != null ?
                new ObjectParameter("SEARCH_KEY", sEARCH_KEY) :
                new ObjectParameter("SEARCH_KEY", typeof(string));
    
            var sORT_COLParameter = sORT_COL != null ?
                new ObjectParameter("SORT_COL", sORT_COL) :
                new ObjectParameter("SORT_COL", typeof(string));
    
            var sORT_DIRParameter = sORT_DIR != null ?
                new ObjectParameter("SORT_DIR", sORT_DIR) :
                new ObjectParameter("SORT_DIR", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SSW_BOARD_PAGING_SEL", sEARCH_COLParameter, sEARCH_KEYParameter, sORT_COLParameter, sORT_DIRParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<SP_SSW_BOARD_PAGING_SEL_no_temptable_Result> SP_SSW_BOARD_PAGING_SEL_no_temptable(string oRDER_OPT, Nullable<int> pAGE, Nullable<int> pAGESIZE)
        {
            var oRDER_OPTParameter = oRDER_OPT != null ?
                new ObjectParameter("ORDER_OPT", oRDER_OPT) :
                new ObjectParameter("ORDER_OPT", typeof(string));
    
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SSW_BOARD_PAGING_SEL_no_temptable_Result>("SP_SSW_BOARD_PAGING_SEL_no_temptable", oRDER_OPTParameter, pAGEParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<SP_TEST_TBOARD_02_SEL_Result> SP_TEST_TBOARD_02_SEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TEST_TBOARD_02_SEL_Result>("SP_TEST_TBOARD_02_SEL");
        }
    
        public virtual ObjectResult<SP_TEST01_Result> SP_TEST01(string sEARCH_COL, string sEARCH_KEYWORD, string sEARCH_KEYWORD2)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var sEARCH_KEYWORD2Parameter = sEARCH_KEYWORD2 != null ?
                new ObjectParameter("SEARCH_KEYWORD2", sEARCH_KEYWORD2) :
                new ObjectParameter("SEARCH_KEYWORD2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TEST01_Result>("SP_TEST01", sEARCH_COLParameter, sEARCH_KEYWORDParameter, sEARCH_KEYWORD2Parameter);
        }
    
        public virtual ObjectResult<SP_TEST02_Result> SP_TEST02(string sEARCH_COL, string sEARCH_KEYWORD, string sEARCH_KEYWORD3)
        {
            var sEARCH_COLParameter = sEARCH_COL != null ?
                new ObjectParameter("SEARCH_COL", sEARCH_COL) :
                new ObjectParameter("SEARCH_COL", typeof(string));
    
            var sEARCH_KEYWORDParameter = sEARCH_KEYWORD != null ?
                new ObjectParameter("SEARCH_KEYWORD", sEARCH_KEYWORD) :
                new ObjectParameter("SEARCH_KEYWORD", typeof(string));
    
            var sEARCH_KEYWORD3Parameter = sEARCH_KEYWORD3 != null ?
                new ObjectParameter("SEARCH_KEYWORD3", sEARCH_KEYWORD3) :
                new ObjectParameter("SEARCH_KEYWORD3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TEST02_Result>("SP_TEST02", sEARCH_COLParameter, sEARCH_KEYWORDParameter, sEARCH_KEYWORD3Parameter);
        }
    
        public virtual ObjectResult<USP_JSH_SEL_TEST_Result> USP_JSH_SEL_TEST(string arg1)
        {
            var arg1Parameter = arg1 != null ?
                new ObjectParameter("arg1", arg1) :
                new ObjectParameter("arg1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_JSH_SEL_TEST_Result>("USP_JSH_SEL_TEST", arg1Parameter);
        }
    
        public virtual int USP_SSW_BOARD_DEL(Nullable<int> iDX)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SSW_BOARD_DEL", iDXParameter);
        }
    
        public virtual int USP_SSW_BOARD_INS(string sUBJECT, string cONTENT, string wRITER)
        {
            var sUBJECTParameter = sUBJECT != null ?
                new ObjectParameter("SUBJECT", sUBJECT) :
                new ObjectParameter("SUBJECT", typeof(string));
    
            var cONTENTParameter = cONTENT != null ?
                new ObjectParameter("CONTENT", cONTENT) :
                new ObjectParameter("CONTENT", typeof(string));
    
            var wRITERParameter = wRITER != null ?
                new ObjectParameter("WRITER", wRITER) :
                new ObjectParameter("WRITER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SSW_BOARD_INS", sUBJECTParameter, cONTENTParameter, wRITERParameter);
        }
    
        public virtual ObjectResult<USP_SSW_BOARD_SEL_Result> USP_SSW_BOARD_SEL(string oRDER_OPT)
        {
            var oRDER_OPTParameter = oRDER_OPT != null ?
                new ObjectParameter("ORDER_OPT", oRDER_OPT) :
                new ObjectParameter("ORDER_OPT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SSW_BOARD_SEL_Result>("USP_SSW_BOARD_SEL", oRDER_OPTParameter);
        }
    
        public virtual int USP_SSW_BOARD_UPD(Nullable<int> iDX, string sUBJECT, string cONTENT, string wRITER)
        {
            var iDXParameter = iDX.HasValue ?
                new ObjectParameter("IDX", iDX) :
                new ObjectParameter("IDX", typeof(int));
    
            var sUBJECTParameter = sUBJECT != null ?
                new ObjectParameter("SUBJECT", sUBJECT) :
                new ObjectParameter("SUBJECT", typeof(string));
    
            var cONTENTParameter = cONTENT != null ?
                new ObjectParameter("CONTENT", cONTENT) :
                new ObjectParameter("CONTENT", typeof(string));
    
            var wRITERParameter = wRITER != null ?
                new ObjectParameter("WRITER", wRITER) :
                new ObjectParameter("WRITER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SSW_BOARD_UPD", iDXParameter, sUBJECTParameter, cONTENTParameter, wRITERParameter);
        }
    }
}
