//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movieStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BOARD_02
    {
        public int IDX { get; set; }
        public string USER_NM { get; set; }
        public string PHONE_NUM { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public Nullable<int> t2 { get; set; }
    }
}
